### ISSUE TITLE
ReturnCode 255

### ISSUE THREAD

**Issue by JoeyL-pf** [ZUGFeRD/ZUV#27]
I don't know why I get returncode "255". Status is "valid"

`root@VM1:/opt/mydir/errors/gcnqe9ecmg6wkwuzwcz3bsaqaxupqctrknx9t1h7# /opt/system/jdkcorretto-8.212.04.2/jre/bin/java -jar ../../bin/ZUV-0.8.3.jar --action validate -f in.xml
<validation><xml><info><version>2</version><profile>urn:cen.eu:en16931:2017</profile><validator version="0.8.3"></validator><validation datetime="2019-12-19 08:07:09"><rules><fired>83</fired><failed>0</failed></rules><duration unit='ms'>8528</duration></validation></info><summary status='valid'/></xml><info><version>2</version><profile>urn:cen.eu:en16931:2017</profile><validator version="0.8.3"></validator><validation datetime="2019-12-19 08:07:09"><rules><fired>83</fired><failed>0</failed></rules><duration unit='ms'>8528</duration></validation></info><summary status='valid'/></validation>

root@VM1:/opt/mydir/errors/gcnqe9ecmg6wkwuzwcz3bsaqaxupqctrknx9t1h7# echo $?
255`

Am I making a mistake?

[in.txt](https://github.com/ZUGFeRD/ZUV/files/3982564/in.txt)

**Comment by jstaerk** [comment]
no your file seems to be valid and the exit code should be 0, it's probably wrong in the software, thanks for the report

**Comment by jstaerk** [comment]
the complete validity was determined by XML AND PDF validity, which was incorrect in case there was no PDF. I patched it, it will be fixed with the next release.
