### ISSUE TITLE
BR-CO-15 error thrown despite correct totals

### ISSUE THREAD

**Issue by rbaiter** [ZUGFeRD/ZUV#38]
Profile: urn:cen.eu:en16931:2017
Despite correct totals entered in SpecifiedTradeSettlementHeaderMonetarySummation trying to validate throws an error referring to BR-CO-15: BT-112 = BT-109 + BT-110

```
<ram:SpecifiedTradeSettlementHeaderMonetarySummation>
            <ram:LineTotalAmount>21618.00</ram:LineTotalAmount>
            <ram:ChargeTotalAmount>0.00</ram:ChargeTotalAmount>
            <ram:AllowanceTotalAmount>0.00</ram:AllowanceTotalAmount>
            <ram:TaxBasisTotalAmount>21618.00</ram:TaxBasisTotalAmount>
            <ram:TaxTotalAmount>4107.42</ram:TaxTotalAmount>
            <ram:GrandTotalAmount>25725.42</ram:GrandTotalAmount>
            <ram:TotalPrepaidAmount>0.00</ram:TotalPrepaidAmount>
            <ram:DuePayableAmount>25725.42</ram:DuePayableAmount
</ram:SpecifiedTradeSettlementHeaderMonetarySummation>
```

**Comment by jstaerk** [comment]
Unfortunately it's very hard to reproduce the issue with only a fragment, could you please submit the rest of the XML?

**Comment by rbaiter** [comment]
Had to anonymize some things, which caused some new errors I didn't have time to fix, I hope that doesnt cause an issue. 
The relevant error persists.
Thanks!
[ZUGFeRD-invoice.zip](https://github.com/ZUGFeRD/ZUV/files/4862595/ZUGFeRD-invoice.zip)

**Comment by jstaerk** [comment]
Among others, TaxTotalAmount requires a currencyID attribute. I once though this was an error in the standard and/or the schematron but in the in the meantime I am no longer sure.  Attached the corrected version.
[zugferd-invoice.zip](https://github.com/ZUGFeRD/ZUV/files/4873087/zugferd-invoice.zip)
