### ISSUE TITLE
Attribute currencyID should be optional

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/ZUV#39]
Betreff: Unklarheit in der Validierung von ZUGFeRD 2.1

Hallo,

ich bin der Entwickler hinter der C#-ZUGFeRD-Bibliothek ZUFeRD-csharp (https://github.com/stephanstapel/ZUGFeRD-csharp).

Im Rahmen der Implementierung der Version 2.1 haben wir das Attribute currencyID wie im Standard vorgesehen so abgebildet, dass es nur im Profil Extended erzeugt wird.

Allerdings ist es so, dass der Validator dann die Summen als nicht korrekt ansieht. Dieser Fehler wurde hier gemeldet:
https://github.com/stephanstapel/ZUGFeRD-csharp/issues/56

Die Fehlermeldung macht deutlich, dass der Selektor für die Validierung offenbar das Attribut currencyID erfordert (obwohl dies nicht vorhanden sein muss):

ram:GrandTotalAmount = round(ram:TaxBasisTotalAmount*100 + ram:TaxTotalAmount[@currencyID=/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:InvoiceCurrencyCode]*100 +0) div 100) or ((ram:GrandTotalAmount = ram:TaxBasisTotalAmount) and not (ram:TaxTotalAmount[@currencyID=/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:InvoiceCurrencyCode]))

Habe ich das so richtig verstanden? Und falls ja: wie muss eine Rechnung dann korrekt aufgebaut werden für Formate < Extended?

**Comment by stephanstapel** [comment]
Hallo Jochen,
hast Du dieses Thema schon weitergegeben? Stand im Juli war, dass currencyId in allen Profilen erlaubt ist, nur die currencyId an TaxBasisTotalAmount ist nur beim Extended-Profile zu nutzen.
Leider schlägt CII-DT-031 immer noch an.

**Comment by jstaerk** [comment]
Mein Stand war dass die auch in en16931 zu setzen ist weil es in en16931 eine 1:2 (originalwährung vs. potenziell vorhandene steuerwährung) und in extended eine 1:n beziehung ist und die währung auch in der 1:1 form angegeben werden muss falls es mal eine 1:2 gäbe...
