### ISSUE TITLE
'@schemeID' is not allowed

### ISSUE THREAD

**Issue by Cakmakli-a** [ZUGFeRD/ZUV#40]
Zum Einsatz kommt ZUV 0.9.0. Den `ZUGFeRDExporter` konfiguriere ich mit zfVersion=2 und ZUGFeRDConformanceLevel.EN16931.
Am Ende der Validierung erhalte folgenden Fehler, den ich mir nicht erklären kann:

`Value of '@schemeID' is not allowed.`

Herausgefunden habe ich, dass 'schemeID' wie folgt vorkommt:

`<ram:SpecifiedTaxRegistration><ram:ID schemeID="VA">`
und
`<ram:SpecifiedLegalOrganization><ram:ID schemeID='9930'>`

Wenn ich die Fehlermeldung "richtig" verstehe, wird in einem oder in beiden Elementen für 'schemeID' kein Wert verlangt.
Kann man den Fehler auf eines oder auf beide Elemente zurückführen !?
Wie kommt der hinterlegte Wert hier zustande?

**Comment by jstaerk** [comment]
Older versions of Mustang erroneously used 9930 in scheme ID, a update should help. In any other case the XML would be helpful.

**Comment by Cakmakli-a** [comment]
[XRechnung.txt](https://github.com/ZUGFeRD/ZUV/files/4994335/XRechnung.txt)

This is the (embedded) XML that causes the mentioned error above.
