### ISSUE TITLE
ZUV works for CII, not for UBL

### ISSUE THREAD

**Issue by homebeaver** [ZUGFeRD/ZUV#45]
Hallo Jochen Staerk @jstaerk,

ich habe den Validator auf der [zugferd-community Seite](https://www.zugferd-community.net/de/dashboard/validation) genutzt.

Und zwar mit einer Rechnung, die als CII xml und als UBL xml verliegt. Die zwei unterschiedlichen Syntaxen sind ja in ZUGFerRD möglich.

- die CII Version wird als valide akzeptiert
- bei der UBL Variante gibt es lt. Validation-Report eine exception und die xml wird als nicht valide markiert.

Kann es sein, dass ZUV nur CII erwartert?

Gruß EUGen H.

**Comment by jstaerk** [comment]
Ja, korrekt, ubl xrechnungen werden nicht unterstützt, übrigens auch nicht vom zugferd referenzprofil. Davon unabhängig ist zuv in mustangproject aufgegangen.

**Comment by homebeaver** [comment]
Danke für die schnelle Antwort.
Dann schlage ich vor, eine Msg auszugeben: "UBL not supported" ... oder so. 
Denn exception + invalid ist nicht angebracht.

Der Validation-Report:
```xml

<?xml version="1.0"?>

<
!--?xml version="1.0" encoding="UTF-8"?-->

-<validation datetime="2020-12-03 12:31:19" filename="1052923-Gutschrift_170827.xml">


-<xml>


-<messages>

<exception type="22">null<stacktrace>java.lang.NullPointerException at 
org.mustangproject.validator.XMLValidator.matchesURI(XMLValidator.java:93) at 
org.mustangproject.validator.XMLValidator.validate(XMLValidator.java:246) at 
org.mustangproject.validator.ZUGFeRDValidator.validate(ZUGFeRDValidator.java:204) at 
org.mustangproject.commandline.Main.performValidate(Main.java:370) at 
org.mustangproject.commandline.Main.main(Main.java:341) </stacktrace></exception>

</messages>

<summary status="invalid"/>

</xml>

<messages/>

<summary status="invalid"/>

</validation>
```

**Comment by jstaerk** [comment]
Da UBL nicht nur nicht unterstützt, sondern im ZUGFeRD-Kontext eben auch falsch ist finde ich eine Exception statt einer Warnung gar nicht mal so dramatisch.
